const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const context=await browser.newContext({viewport:{width:1440,height:900}});
  await context.route('https://www.gstatic.com/firebasejs/**',r=>r.fulfill({body:'/* isolated preview adapter */',contentType:'text/javascript'}));
  const errors=[],checks=[],out=path.resolve(__dirname,'../검증');fs.mkdirSync(out,{recursive:true});
  const base='http://127.0.0.1:4173/?demo=1&session=verify-'+Date.now();
  const open=async query=>{const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+query);await p.waitForFunction(()=>window.QPGame&&window.QPDemo&&window.QPAvatar?.atlas.ready===true&&window.QPClothes?.atlas.ready===true);return p;};
  const host=await open('&role=teacher');await host.waitForFunction(()=>QPGame.getHost());
  const a=await open('&user=하늘'),b=await open('&user=민트'),c=await open('&user=유리');
  for(const p of [a,b,c])await p.waitForSelector('#meStage');
  const read=()=>host.evaluate(()=>QPGame.getHost().room);
  const waitRoom=async (fn,arg)=>host.waitForFunction(fn,arg);
  const gold=p=>p.evaluate(()=>QPGame.getMe().gold);
  const start=async(mode,count=2,sec=20)=>{
    await host.evaluate(async({mode,count,sec})=>QPGame.getHost().open(mode,mode==='ox'?'demo_ox':'demo_quiz',count,sec,mode==='cross'?'동물':null),{mode,count,sec});
    for(const p of[a,b,c])await p.evaluate(()=>QPGame.go('live'));
    await waitRoom(()=>Object.keys(QPGame.getHost().room.p||{}).length===3);
    await host.evaluate(()=>QPGame.getHost().start());
    await waitRoom(()=>QPGame.getHost().meta.phase==='ask');
  };
  const answer=()=>host.evaluate(()=>{const m=QPGame.getHost().meta;return pickQs(m.setId,m.seed,m.count,m.mode==='ox')[m.qi].a.split('/')[0];});
  const submit=async(p,v)=>{await p.locator('#ansIn').fill(v);await p.locator('#qpAnswerForm').evaluate(f=>f.requestSubmit());};
  await start('quiz');
  const correct=await answer(),initialGold=await gold(a);
  await submit(a,'틀린답');
  await a.waitForFunction(()=>document.querySelector('.qp-feedback')?.textContent.includes('다시'));
  assert.equal((await read()).p.demo_하늘.sc,0);
  assert.equal(await a.locator('#ansIn').isEnabled(),true);
  await submit(a,correct);
  await waitRoom(()=>QPGame.getHost().room.p.demo_하늘.qGood===0);
  await b.waitForTimeout(450);await submit(b,correct);
  await waitRoom(()=>QPGame.getHost().room.p.demo_민트.qGood===0);
  let r=await read();assert(r.p.demo_하늘.sc>r.p.demo_민트.sc);
  const before=r.p.demo_하늘.sc;
  await a.evaluate(async v=>{const m=(await QPDemo.db.ref('quiz/room/meta').once()).val();await QPDemo.db.ref('quiz/room/try').push({session:m.session,qi:m.qi,by:'demo_하늘',v,t:Date.now()}).set({session:m.session,qi:m.qi,by:'demo_하늘',v,t:Date.now()});},correct);
  await waitRoom(()=>!Object.keys(QPGame.getHost().room.try||{}).length);
  assert.equal((await read()).p.demo_하늘.sc,before);
  await a.waitForFunction(g=>QPGame.getMe().gold===g+25,initialGold);
  assert.equal(await gold(a),initialGold+25);
  checks.push('Typed wrong-answer retry, faster correct score, duplicate-answer and duplicate-gold protection');
  await a.screenshot({path:path.join(out,'빠른퀴즈.png')});
  await host.evaluate(()=>QPGame.getHost().reveal());
  await host.evaluate(()=>QPGame.getHost().next());
  await waitRoom(()=>QPGame.getHost().meta.qi===1&&QPGame.getHost().meta.phase==='ask');
  await a.waitForSelector('#ansIn');assert.equal(await a.locator('#ansIn').isEnabled(),true);
  await host.evaluate(()=>QPGame.getHost().reveal());await host.evaluate(()=>QPGame.getHost().end());
  await waitRoom(()=>QPGame.getHost().meta.phase==='end');await a.waitForSelector('.qp-results');
  checks.push('Next question resets answer input and end screen appears');

  await start('ox',2,15);
  const oxAnswer=await answer(),rightZone=oxAnswer==='O'?'0':'1',wrongZone=rightZone==='0'?'1':'0';
  await a.locator('[data-z="'+wrongZone+'"]').click();await b.locator('[data-z="'+rightZone+'"]').click();await c.locator('[data-z="'+rightZone+'"]').click();
  await waitRoom(()=>Object.keys(QPGame.getHost().room.ans||{}).length===3);
  assert.equal((await read()).meta.phase,'ask');
  await b.locator('[data-z="'+wrongZone+'"]').click();await b.locator('[data-z="'+rightZone+'"]').click();
  await waitRoom(({right})=>QPGame.getHost().room.p.demo_민트.ox===Number(right),{right:rightZone});
  await a.screenshot({path:path.join(out,'OX게임.png')});
  await host.evaluate(()=>QPGame.getHost().reveal());
  r=await read();assert.equal(r.p.demo_하늘.sc,0);assert.notEqual(r.p.demo_하늘.alive,false);assert.equal(r.p.demo_민트.sc,100);
  await host.evaluate(()=>QPGame.getHost().next());
  await waitRoom(()=>QPGame.getHost().meta.qi===1&&QPGame.getHost().meta.phase==='ask');
  const nextOx=await answer();await a.locator('[data-z="'+(nextOx==='O'?'0':'1')+'"]').click();
  await host.evaluate(()=>QPGame.getHost().reveal());
  assert.equal((await read()).p.demo_하늘.sc,100);
  checks.push('OX permits switching until deadline, does not end early, keeps incorrect players for next question');

  await start('cross',7,120);
  r=await read();const keys=Object.keys(r.meta.memberTeams),pairTeam=['A','B'].find(t=>keys.filter(k=>r.meta.memberTeams[k]===t).length===2);
  const teammates=keys.filter(k=>r.meta.memberTeams[k]===pairTeam),other=keys.find(k=>r.meta.memberTeams[k]!==pairTeam);
  const pages={'demo_하늘':a,'demo_민트':b,'demo_유리':c};
  const solver=pages[teammates[0]],mate=pages[teammates[1]],opponent=pages[other];
  const puzzle=await host.evaluate(()=>{const m=QPGame.getHost().meta;return buildCross(topicWords(m.topic),m.seed,m.count);});
  const word=puzzle.w[0],points=100+word.len*20;
  const gs=await gold(solver),gm=await gold(mate),go=await gold(opponent);
  await solver.locator('[data-clue="'+word.n+'"]').click();await solver.locator('#cIn').fill(word.a);await solver.locator('#crossForm').evaluate(f=>f.requestSubmit());
  await host.waitForFunction(({team,n})=>QPGame.getHost().room.cross.teams[team].f?.[n],{team:pairTeam,n:word.n});
  await mate.waitForFunction(n=>document.querySelector('[data-clue="'+n+'"]')?.classList.contains('done'),word.n);
  r=await read();assert.equal(r.cross.teams[pairTeam].score,points);assert.equal(Object.keys(r.cross.teams[pairTeam==='A'?'B':'A'].f||{}).length,0);
  await solver.waitForFunction(g=>QPGame.getMe().gold===g+25,gs);await mate.waitForFunction(g=>QPGame.getMe().gold===g+25,gm);
  assert.equal(await gold(opponent),go);
  await mate.evaluate(async({n,v})=>{const m=(await QPDemo.db.ref('quiz/room/meta').once()).val();await QPDemo.db.ref('quiz/room/try').push({session:m.session,qi:m.qi,by:QPGame.getMe().k,n,v,t:Date.now()}).set({session:m.session,qi:m.qi,by:QPGame.getMe().k,n,v,t:Date.now()});},{n:word.n,v:word.a});
  await waitRoom(()=>!Object.keys(QPGame.getHost().room.try||{}).length);
  assert.equal((await read()).cross.teams[pairTeam].score,points);assert.equal(await gold(mate),gm+25);
  await solver.screenshot({path:path.join(out,'팀가로세로.png')});
  checks.push('Team crossword synchronizes teammates, keeps opponent board independent, credits each teammate exactly once');

  await a.evaluate(()=>QPGame.go('shop'));await a.locator('#shTabs [data-c="expression"]').click();
  const g=await gold(a);await a.locator('#shGrid [data-id="expression:happy:0"]').click();await a.locator('#btnBuy').click();
  await a.waitForFunction(()=>QPGame.getMe().owned['expression:happy:0']&&QPGame.getMe().av.expression==='happy:0');
  assert.equal(await gold(a),g-220);
  const first=await a.locator('#pvStage .qpx-body').evaluate(e=>e.getAnimations()[0].currentTime);
  await a.waitForTimeout(80);const second=await a.locator('#pvStage .qpx-body').evaluate(e=>e.getAnimations()[0].currentTime);assert(second>first);
  const times=await a.evaluate(()=>document.querySelector('#pvStage svg').getAnimations({subtree:true}).filter(x=>['qpx-body','qpx-hands','qpx-blink-half','qpx-blink-closed'].includes(x.animationName)).map(x=>({name:x.animationName,time:x.currentTime,iterations:x.effect.getTiming().iterations})));
  assert(times.length>=3&&times.every(t=>t.iterations===Infinity));
  checks.push('Paid face buying/equipping debits exact price; breathing and blink continue in fitting preview');
  await a.locator('#shTabs [data-c="hair"]').click();
  assert.equal(await a.locator('#shGrid [data-id]').count(),8);
  await a.locator('#shopOwned').click();
  assert(await a.locator('#shGrid [data-id="hair:bob:1"]').count());
  assert(await a.locator('#shGrid [data-id="hair:bob:5"]').count());
  const priorGender=await a.evaluate(()=>JSON.stringify({av:QPGame.getMe().av,owned:QPGame.getMe().owned,gold:QPGame.getMe().gold}));
  await a.locator('#btnGender').click();
  assert.equal(await a.locator('#avatarSexChoices .qp-pixel-avatar').count(),2);
  const genderSources=await a.locator('#avatarSexChoices image[data-qpx-sex]:not([data-qpx-tail])').evaluateAll(es=>es.map(e=>e.getAttribute('href')));
  assert.equal(genderSources.length,2);assert.notEqual(genderSources[0],genderSources[1]);
  await a.locator('#avatarSexChoices button[data-sex="m"]').click();
  await a.waitForFunction(()=>QPGame.getMe().av.sex==='m');
  const afterGender=await a.evaluate(()=>({av:QPGame.getMe().av,owned:QPGame.getMe().owned,gold:QPGame.getMe().gold}));
  const prior=JSON.parse(priorGender);assert.equal(afterGender.gold,prior.gold);assert.deepEqual(afterGender.owned,prior.owned);assert.deepEqual({...afterGender.av,sex:prior.av.sex,hair:prior.av.hair},prior.av);
  assert(['short','part','messy','spiky'].includes(afterGender.av.hair.split(':')[0]));
  checks.push('Male and female have different drawn heads; switching is free and preserves clothing, owned items and gold');
  await a.locator('#btnFace').click();await a.locator('#fSk button[data-i="4"]').click();
  assert.equal(await a.evaluate(()=>QPGame.getMe().av.sk),4);
  const skin=await a.locator('#pvStage .qpx-body [fill]').evaluateAll(es=>es.map(e=>e.getAttribute('fill')));
  assert(skin.includes(await a.evaluate(()=>PAL.skin[4][0])));
  checks.push('Separate male and female hair shops, owned hair colors together in wardrobe, skin changes body palette');
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'검증결과.json'),JSON.stringify({checks,errors,viewport:'1440x900, three simultaneous player pages and a host',motion:times},null,2));
  console.log(JSON.stringify({passed:checks,errors},null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
