'use strict';
/* Garment index (stage 3): assets/sd-garments-index.js → QPFoundationGarmentIndex.

     node tools/garment/build-index.cjs           regenerate from the assets/sd-garment-<cat>-<shape>.js records
     node tools/garment/build-index.cjs --check   fail when the committed index is stale or a record is invalid

   Generated deterministically (sorted keys, no dates); after a merge conflict
   rerun the tool instead of merging by hand. Every record is validated against
   tools/garment/schema.json with the frozen-body context and its atlas files.

   {schema:1, generator, records:{id:{slot,class,status,legacy,sexes,sha256,files}},
    catalogue:{'sex:cat:shape':id}, starter:{m|f:{top,bottom,shoes}}, starterItems, runtimeClasses}

   Lookup is by (sex, cat, shape); the colour index ci is ignored (kept per sex
   in each record as a legacy token). A shelf item with no catalogue key falls
   back with reason 'todo' (e.g. the male default bottom:jeans:5 today).
   Not loaded by index.html yet: the runtime registry comes in WP3, which also
   wires `require('./garment/build-index.cjs')(true)` into tools/check-source.cjs. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const S=require('./schema.cjs');
const root=path.resolve(__dirname,'..','..'),TARGET='assets/sd-garments-index.js';

// User decision 2026-10-09 (퀴즈나라/AGENTS.md): the basic outfit of the base
// character is the free starter items — boys top:tee:5, bottom:shorts:9;
// girls top:tee:3, bottom:shorts:5; both shoes:sneaker:8. (A new boy's
// account keeps bottom:jeans:5 until the stage-5 switch; that is not changed here.)
const STARTER={
  m:{top:'top:tee:5',bottom:'bottom:shorts:9',shoes:'shoes:sneaker:8'},
  f:{top:'top:tee:3',bottom:'bottom:shorts:5',shoes:'shoes:sneaker:8'}
};

const sortKeys=o=>Object.fromEntries(Object.keys(o).sort().map(k=>[k,o[k]]));
// One key per line; short lists of plain values on one line.
function pretty(v,indent=0){
  const flat=JSON.stringify(v);if(v===null||typeof v!=='object'||Array.isArray(v)&&!flat.includes('{')&&flat.length<=100)return flat;
  const pad=' '.repeat(indent),inner=' '.repeat(indent+1);
  if(Array.isArray(v))return'[\n'+v.map(x=>inner+pretty(x,indent+1)).join(',\n')+'\n'+pad+']';
  const keys=Object.keys(v);if(!keys.length)return'{}';
  return'{\n'+keys.map(k=>inner+JSON.stringify(k)+':'+pretty(v[k],indent+1)).join(',\n')+'\n'+pad+'}';
}

function collect(){
  const context=S.loadContext(root),records={},problems=[],shas={};
  for(const file of S.dataFiles(root)){
    const parsed=S.parseFile(file);let r,text;
    try{({record:r,text}=S.readDataFile(path.join(root,file)));}catch(error){problems.push(file+': '+error.message);continue;}
    if(!parsed||parsed.id!==r.id)problems.push(file+': registers '+r.id+', file name says '+(parsed?.id||'?'));
    if(records[r.id])problems.push(file+': second record for '+r.id);
    for(const i of S.validate(r,{context,root}))problems.push(file+': '+i.code+' '+i.path+': '+i.message);
    records[r.id]=r;shas[r.id]=S.sha256(text);
  }
  return{records,problems,shas};
}

function makeIndex(records,shas){
  const index={schema:1,generator:'tools/garment/build-index.cjs',records:{},catalogue:{},starter:{},starterItems:{},runtimeClasses:[...S.RUNTIME_CLASSES].sort()};
  for(const id of Object.keys(records).sort()){
    const r=records[id],sexes=Object.keys(r.sexes).sort();
    if(r.status==='retired')continue;
    index.records[id]={slot:r.slot,class:r.class,status:r.status,legacy:r.legacy,sexes,sha256:shas[id],files:S.filesFor(id,sexes)};
    for(const sex of sexes)index.catalogue[sex+':'+r.cat+':'+r.shape]=id;
  }
  index.catalogue=sortKeys(index.catalogue);
  for(const sex of ['m','f']){
    index.starter[sex]={};index.starterItems[sex]={};
    for(const slot of ['top','bottom','shoes']){const item=STARTER[sex][slot],[cat,shape]=item.split(':');
      index.starter[sex][slot]=index.catalogue[sex+':'+cat+':'+shape]||null;index.starterItems[sex][slot]=item;}
  }
  return index;
}

function render(index){
  return'/* Generated by tools/garment/build-index.cjs from the assets/sd-garment-*.js records. Do not edit;\n'+
    '   rerun the tool (also after a merge conflict). Lookup: catalogue[sex+\':\'+cat+\':\'+shape] → record id. */\n'+
    '(function(root){\n\'use strict\';\nconst index='+pretty(index)+';\n'+
    'const freeze=o=>{if(o&&typeof o===\'object\'&&!Object.isFrozen(o)){Object.freeze(o);for(const v of Object.values(o))freeze(v);}return o;};\n'+
    'root.QPFoundationGarmentIndex=freeze(index);\n'+
    '})(typeof window===\'undefined\'?globalThis:window);\n';
}

function build(check=false){
  const {records,problems,shas}=collect();
  const index=makeIndex(records,shas);
  for(const i of S.validateIndex(index,{records}))problems.push(TARGET+': '+i.path+': '+i.message);
  assert.equal(problems.length,0,'Garment records or index invalid:\n  '+problems.join('\n  '));
  const text=render(index),file=path.join(root,TARGET);
  if(check)assert.equal(fs.existsSync(file)&&fs.readFileSync(file,'utf8')===text,true,'Garment index is stale. Run node tools/garment/build-index.cjs');
  else if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==text)fs.writeFileSync(file,text);
  console.log(TARGET+' '+(check?'matches':'holds')+' '+Object.keys(index.records).length+' garment records, '+Object.keys(index.catalogue).length+' catalogue keys');
  return index;
}
module.exports=build;
module.exports.build=build;
module.exports.STARTER=STARTER;
module.exports.makeIndex=makeIndex;
module.exports.render=render;
if(require.main===module){try{build(process.argv.includes('--check'));}catch(error){console.error(error.message);process.exit(1);}}
