import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { serve } from './serve2.mjs';
const srv = serve(8851, '/home/user/game/index.html');
const b = await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox']});
const pg = await b.newPage({viewport:{width:1100,height:700}});
const errs=[]; pg.on('pageerror', e=> errs.push('PAGEERROR: '+e.message+' | '+(e.stack||'').split('\n')[1]));
pg.on('console', m=>{ if(m.type()==='error') errs.push('CONSOLE: '+m.text()); });
await pg.goto('http://127.0.0.1:8851/?diag=1', {waitUntil:'load', timeout:60000});
await pg.waitForFunction('window.__READY===true', {timeout:60000});
await pg.fill('#iName','김하늘'); await pg.click('#bSolo'); await pg.waitForTimeout(1200);
await pg.evaluate(()=>{ document.querySelectorAll('.pop').forEach(e=>e.classList.remove('on')); });
await pg.waitForTimeout(2500);
console.log(errs.length ? errs.slice(0,6).join('\n') : '(로드·구동 오류 없음)');
await b.close(); srv.close();
